# Generated by Django 2.1.5 on 2019-06-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(default='https://www.freeiconspng.com/uploads/user-icon-png-person-user-profile-icon-20.png', upload_to='profile_pic'),
        ),
    ]
