# Generated by Django 2.1.5 on 2019-06-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190615_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(default='\\static/profile.png', upload_to='profile_pic'),
        ),
    ]
