# Generated by Django 2.1.5 on 2019-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190615_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(default='/home/pramodjaiswal/webdev/Feedly/static/profile.png', upload_to='profile_pic'),
        ),
    ]
