# Generated by Django 2.1.5 on 2019-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190615_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(default='profile_pic/profile.png', upload_to='profile_pic'),
        ),
    ]
