# Generated by Django 2.1.5 on 2019-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190617_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(default='profile.png', upload_to='profile_pic'),
        ),
    ]
