# Generated by Django 2.1.5 on 2019-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190617_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(default='post_pics/profile.png', upload_to='profile_pic'),
        ),
    ]
