# Generated by Django 2.1.1 on 2018-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
