# Generated by Django 2.1.1 on 2018-09-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='username',
        ),
    ]
