# Generated by Django 2.1.1 on 2018-09-26 07:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('result', django.db.models.manager.Manager()),
            ],
        ),
    ]
