# Generated by Django 2.1.1 on 2018-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post_video_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
